RL_algo: SAC

train:
  total_timesteps: 10000000
  save_freq: 50000
  # pretrained: 'tb_log/SAC_12'
  pretrained: null

model:
  tensorboard_log: "tb_log"
  learning_rate: 0.0003
  buffer_size: 1000000
  learning_starts: 50000
  batch_size: 256
  tau: 0.05
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  policy_kwargs:
    net_arch: 
      pi: [128,128]
      qf: [128,128]
    activation_fn: Tanh
    
  

env_kwargs:
  # observable: [pos, quaternion, rpy, vel, angular_vel, rpm]
  # observable: [rpy, vel, angular_vel, rpm]
  observable: [pos,rotation, vel, angular_vel, rpm]
  frame_stack: 1
  task: stabilize2
  rpy_noise: 0.8
  vel_noise: 1.0
  angvel_noise: 1.5
  reward_coeff: # only for stabilizing task
    xyz: 1
    # rpy: 4
    # rotation: 0.1
    vel: 0.02
    ang_vel: 0.1
    # action: 1
    d_action: 0.01
  episode_len_sec: 2
  max_rpm: 65535 # 2^16-1
  initial_xyzs: [[0.0,0.0,1.0]]